// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQyXCerWhcpBx3HG9Z98YhEXShl89xi4A',
    appId: '1:162007386982:web:227e4c68f1ebb192d596a7',
    messagingSenderId: '162007386982',
    projectId: 'graduationmovies',
    authDomain: 'graduationmovies.firebaseapp.com',
    storageBucket: 'graduationmovies.firebasestorage.app',
    measurementId: 'G-JHQ6XY8ERE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8megPprd23cVnHFDbPPRysJrSrQFx-8s',
    appId: '1:162007386982:android:ee9a9718d69e643cd596a7',
    messagingSenderId: '162007386982',
    projectId: 'graduationmovies',
    storageBucket: 'graduationmovies.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4F3t8J-AwGllihgeRl6dR3G0K2EI1bns',
    appId: '1:162007386982:ios:8b3004e22d472a50d596a7',
    messagingSenderId: '162007386982',
    projectId: 'graduationmovies',
    storageBucket: 'graduationmovies.firebasestorage.app',
    iosBundleId: 'com.example.greduationMoviesFluter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4F3t8J-AwGllihgeRl6dR3G0K2EI1bns',
    appId: '1:162007386982:ios:8b3004e22d472a50d596a7',
    messagingSenderId: '162007386982',
    projectId: 'graduationmovies',
    storageBucket: 'graduationmovies.firebasestorage.app',
    iosBundleId: 'com.example.greduationMoviesFluter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQyXCerWhcpBx3HG9Z98YhEXShl89xi4A',
    appId: '1:162007386982:web:c6d4306a0a68bb26d596a7',
    messagingSenderId: '162007386982',
    projectId: 'graduationmovies',
    authDomain: 'graduationmovies.firebaseapp.com',
    storageBucket: 'graduationmovies.firebasestorage.app',
    measurementId: 'G-R5CXD5YLYC',
  );
}
